# service node type, [DN|CN|LOG]
service-type = "LOG"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512


[observability]
status-port = 7001

[[fileservice]]
name = "SHARED"
backend = "S3"

[fileservice.s3]
endpoint = "DISK"
bucket = "mo-data/shared"
